[book]
title = "The Darkmatter RFC Book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/darkmatter-lang/rfcs"
site-url = "/rfcs/"

[output.html.search]
heading-split-level = 0

[output.html.playground]
runnable = false
